### ISSUE TITLE
Merge Events to new Activities tab

### ISSUE THREAD

**Issue by ahaumann** [iapsoecs/iapsoecs.github.io#3]
- Replace "Events" in menu with "Activities" tab and make "Events" a sub-item
- Add upcoming IAPSO/ IAPSO ECS events on landing page and link to "Events" tab for details with a heading "Upcoming IAPSO ECS Events".
- Add "IPCC AR6 group review" tab to "Activities"
- Add "UN Decade of Ocean Science"  tab to "Activities"
- Add "Educational" to "Activities"? Or a menu-item by itself?

**Comment by isopycn-ale** [comment]
We could add these opportunities under postdoctoral fellowships subitems:
www.nerc.ac.uk/funding/available/fellowships/irf/
www.esprc.ac.uk/funding/calls/inclusionmatters/
https://www.ukri.org/funding/funding-opportunities/future-leaders-fellowships/
https://royalsociety.org/grants-schemes-awards/grants/dorothy-hodgkin-fellowship/ 
https://royalsociety.org/grants-schemes-awards/grants/newton-international/ 
https://royalsociety.org/grants-schemes-awards/grants/newton-advanced-fellowships/
https://nerc.ukri.org/funding/available/researchgrants/standard/
https://ec.europa.eu/research/mariecurieactions/actions/individual-fellowships_en

**Comment by jessecusack** [comment]
@isopycn-ale I added those links to the fellowships page.

**Comment by jessecusack** [comment]
@ahaumann I have made a start of doing this including creating an activities tab and putting some outreach materials.
