### ISSUE TITLE
Merge Career and Jobs

### ISSUE THREAD

**Issue by ahaumann** [iapsoecs/iapsoecs.github.io#4]
As discussed previously. "Career" and "Jobs" menu items could be merged into one item with sub-items

**Comment by jessecusack** [comment]
I thought I had fixed this but in doing so I have broken the usage for phone users. Will update shortly.

**Comment by jessecusack** [comment]
I think that we should re-consider this merger. Reasons:
1) We want the job ads page to be prominent and obvious for greatest exposure. 
2) Making the 'parent' navigation bar link to a url breaks functionality for phone users who cannot 'hover' a mouse over the link. 
3) Now I removed the little avatar circle IUGG logo, there is a less pressing need for navbar space.
